language: go
install:
  - go get github.com/suveng/ink
  - ink build

script:
  - cd ./blog/public/
  - git init
  - git config user.name "suveng"
  - git config user.email "suveng@163.com"
  - git add .
  - git commit -m "update blogs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  - java --version

branch:
  only:
    -source
env:
  global:
    - GH_REF: github.com/suveng/blog
