language: go
install:
  - go get github.com/suveng/ink
  - ink build

script:
  - cd ./blog/public/
  - git init
  - git config user.name "suveng"
  - git config user.email "suveng@163.com"
  - git add .
  - git commit -m "update blogs"
  # github pages
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  # coding pages
  - git push --force --quiet "https://suveng:${CO_TOKEN}@${CO_REF}" master:master
  # seo
  - curl http://www.google.com/ping?sitemap=https://suveng.github.io/blog/sitemap.xml
branch:
  only:
    -source
env:
  global:
    - GH_REF: github.com/suveng/blog
    - CO_REF: git.dev.tencent.com/suveng/blog.git
