language: go
install:
  - go get github.com/suveng/ink
  - ink build

script:
  - cd ./blog/public/
  - git init
  - git config user.name "suveng"
  - git config user.email "suveng@163.com"
  - git add .
  - git commit -m "update blogs"
  # github pages
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
    # gitee pages
  - git push --force --quiet "https://suveng:${GE_TOKEN}@${GE_REF}" master:master
  # seo
  - curl http://www.google.com/ping?sitemap=https://suveng.github.io/blog/sitemap.xml
branch:
  only:
    -source
notifications:
   webhooks: https://oapi.dingtalk.com/robot/send?access_token=aa9bfcb2f8c5f3a30e2d5e0235b45920eef3aa893be546f51be8f8b0d602c467
env:
  global:
    - GH_REF: github.com/suveng/blog
    - CO_REF: git.dev.tencent.com/suveng/blog.git
    - GE_REF: gitee.com/suveng/blog.git
