language: go
install:
  - go get github.com/suveng/ink
  - ink build

script:
  - cd ./docs
  - git init
  - git config user.name "suveng"
  - git config user.email "suveng@163.com"
  - git add .
  - git commit -m "update"
  - git push --force --quiet "https://${GH_TOKEN}@{GH_REF}" master:master

branch:
  only:
    -source
env:
  global:
    - GH_REF: github.com/suveng/blog